import type { ActiveSegmentData, AnsiColor } from "@/types/prompt";
import { getSegmentById } from "./segments";

const ZSH_FG_MAP: Record<AnsiColor, string> = {
  default: "",
  black: "black",
  red: "red",
  green: "green",
  yellow: "yellow",
  blue: "blue",
  magenta: "magenta",
  cyan: "cyan",
  white: "white",
  bold_black: "black",
  bold_red: "red",
  bold_green: "green",
  bold_yellow: "yellow",
  bold_blue: "blue",
  bold_magenta: "magenta",
  bold_cyan: "cyan",
  bold_white: "white",
};

const CSS_COLOR_MAP: Record<AnsiColor, string> = {
  default: "inherit",
  black: "#1e1e1e",
  red: "#e06c75",
  green: "#98c379",
  yellow: "#e5c07b",
  blue: "#61afef",
  magenta: "#c678dd",
  cyan: "#56b6c2",
  white: "#dcdfe4",
  bold_black: "#5c6370",
  bold_red: "#e06c75",
  bold_green: "#98c379",
  bold_yellow: "#e5c07b",
  bold_blue: "#61afef",
  bold_magenta: "#c678dd",
  bold_cyan: "#56b6c2",
  bold_white: "#ffffff",
};

const CSS_BG_COLOR_MAP: Record<AnsiColor, string> = {
  default: "transparent",
  black: "#1e1e1e",
  red: "#e06c75",
  green: "#98c379",
  yellow: "#e5c07b",
  blue: "#61afef",
  magenta: "#c678dd",
  cyan: "#56b6c2",
  white: "#dcdfe4",
  bold_black: "#5c6370",
  bold_red: "#e06c75",
  bold_green: "#98c379",
  bold_yellow: "#e5c07b",
  bold_blue: "#61afef",
  bold_magenta: "#c678dd",
  bold_cyan: "#56b6c2",
  bold_white: "#ffffff",
};

export function getCssColor(color: AnsiColor): string {
  return CSS_COLOR_MAP[color];
}

export function getCssBgColor(color: AnsiColor): string {
  return CSS_BG_COLOR_MAP[color];
}

function isBold(color: AnsiColor): boolean {
  return color.startsWith("bold_");
}

function wrapWithColor(code: string, fg: AnsiColor, bg: AnsiColor): string {
  if (fg === "default" && bg === "default") return code;

  const parts: string[] = [];
  const bold = isBold(fg) || isBold(bg);

  if (bold) parts.push("%B");

  if (fg !== "default" && bg !== "default") {
    parts.push(`%F{${ZSH_FG_MAP[fg]}}%K{${ZSH_FG_MAP[bg]}}${code}%k%f`);
  } else if (fg !== "default") {
    parts.push(`%F{${ZSH_FG_MAP[fg]}}${code}%f`);
  } else if (bg !== "default") {
    parts.push(`%K{${ZSH_FG_MAP[bg]}}${code}%k`);
  }

  if (bold) parts.push("%b");

  return parts.join("");
}

export function generatePromptString(segments: ActiveSegmentData[]): string {
  return segments
    .map((seg) => {
      const def = getSegmentById(seg.segmentId);
      if (!def) return "";
      return wrapWithColor(def.code, seg.fg, seg.bg);
    })
    .join("");
}

export function generateZshrc(segments: ActiveSegmentData[]): string {
  const promptString = generatePromptString(segments);
  const lines = [
    "# Oh My Zsh Prompt Configuration",
    "# Generated by OhMyZsh Prompt Builder",
    "",
    "# Set the prompt",
    'PROMPT=\'' + promptString + "'",
    "",
    "# To use this prompt:",
    "# 1. Copy this file to your home directory as .zshrc",
    "#    or add the PROMPT line to your existing .zshrc",
    "# 2. Restart your terminal or run: source ~/.zshrc",
    "#",
    "# Note: Some features require Oh My Zsh to be installed.",
    '# Install: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"',
    "",
  ];
  return lines.join("\n");
}

export function getMockPreview(segments: ActiveSegmentData[]): Array<{
  text: string;
  fg: AnsiColor;
  bg: AnsiColor;
}> {
  return segments
    .map((seg) => {
      const def = getSegmentById(seg.segmentId);
      if (!def) return null;
      return {
        text: def.mockValue,
        fg: seg.fg,
        bg: seg.bg,
      };
    })
    .filter(
      (x): x is { text: string; fg: AnsiColor; bg: AnsiColor } => x !== null
    );
}
