import type { ActiveSegmentData, PresetTheme } from "@/types/prompt";

function seg(
  segmentId: string,
  fg: ActiveSegmentData["fg"] = "default",
  bg: ActiveSegmentData["bg"] = "default"
): ActiveSegmentData {
  return {
    instanceId: `preset-${segmentId}-${Math.random().toString(36).slice(2, 8)}`,
    segmentId,
    fg,
    bg,
  };
}

export const PRESETS: PresetTheme[] = [
  {
    id: "robbyrussell",
    name: "robbyrussell",
    description: "The classic Oh My Zsh default theme",
    segments: [
      seg("chevron", "bold_green"),
      seg("space"),
      seg("directory", "cyan"),
      seg("space"),
      seg("paren_open", "blue"),
      seg("git_branch", "red"),
      seg("git_dirty", "yellow"),
      seg("paren_close", "blue"),
      seg("space"),
    ],
  },
  {
    id: "agnoster",
    name: "agnoster",
    description: "Powerline-style theme with rich info",
    segments: [
      seg("username", "white", "blue"),
      seg("at_sign", "white", "blue"),
      seg("hostname", "white", "blue"),
      seg("space"),
      seg("directory", "white", "cyan"),
      seg("space"),
      seg("paren_open", "blue"),
      seg("git_branch", "bold_yellow"),
      seg("git_dirty", "red"),
      seg("paren_close", "blue"),
      seg("space"),
      seg("dollar", "bold_white"),
    ],
  },
  {
    id: "minimal",
    name: "minimal",
    description: "Clean and simple prompt",
    segments: [
      seg("short_dir", "blue"),
      seg("space"),
      seg("chevron", "magenta"),
      seg("space"),
    ],
  },
  {
    id: "clean",
    name: "clean",
    description: "Two-line informative prompt",
    segments: [
      seg("username", "green"),
      seg("at_sign"),
      seg("hostname", "green"),
      seg("colon"),
      seg("directory", "bold_blue"),
      seg("space"),
      seg("paren_open"),
      seg("git_branch", "yellow"),
      seg("paren_close"),
      seg("newline"),
      seg("dollar"),
    ],
  },
  {
    id: "refined",
    name: "refined",
    description: "Elegant with timestamps and git info",
    segments: [
      seg("bracket_open", "bold_black"),
      seg("time_24h", "bold_white"),
      seg("bracket_close", "bold_black"),
      seg("space"),
      seg("username", "bold_cyan"),
      seg("colon"),
      seg("directory", "bold_blue"),
      seg("space"),
      seg("paren_open", "bold_black"),
      seg("git_branch", "bold_magenta"),
      seg("git_dirty", "bold_red"),
      seg("paren_close", "bold_black"),
      seg("newline"),
      seg("chevron", "bold_green"),
      seg("space"),
    ],
  },
  {
    id: "powerline",
    name: "powerline",
    description: "Powerline arrows with colored segments",
    segments: [
      seg("space", "white", "blue"),
      seg("username", "bold_white", "blue"),
      seg("space", "white", "blue"),
      seg("arrow_powerline", "blue", "cyan"),
      seg("space", "white", "cyan"),
      seg("directory", "bold_white", "cyan"),
      seg("space", "white", "cyan"),
      seg("arrow_powerline", "cyan", "green"),
      seg("space", "bold_white", "green"),
      seg("git_branch", "bold_white", "green"),
      seg("space", "white", "green"),
      seg("arrow_powerline", "green"),
      seg("space"),
    ],
  },
  {
    id: "lambda",
    name: "lambda",
    description: "Lambda symbol with minimal info",
    segments: [
      seg("lambda", "bold_magenta"),
      seg("space"),
      seg("directory", "cyan"),
      seg("space"),
      seg("git_branch", "yellow"),
      seg("git_dirty", "red"),
      seg("space"),
    ],
  },
  {
    id: "pure",
    name: "pure",
    description: "Pretty, minimal, and fast — inspired by sindresorhus/pure",
    segments: [
      seg("directory", "blue"),
      seg("space"),
      seg("git_branch", "bold_black"),
      seg("git_dirty", "magenta"),
      seg("newline"),
      seg("chevron", "magenta"),
      seg("space"),
    ],
  },
  {
    id: "spaceship",
    name: "spaceship",
    description: "Feature-rich with runtime info",
    segments: [
      seg("directory", "bold_cyan"),
      seg("space"),
      seg("git_branch", "bold_magenta"),
      seg("git_dirty", "bold_yellow"),
      seg("space"),
      seg("node_version", "bold_green"),
      seg("newline"),
      seg("chevron", "bold_green"),
      seg("space"),
    ],
  },
  {
    id: "bullet_train",
    name: "bullet-train",
    description: "Powerline-based with time, dir, and git",
    segments: [
      seg("space", "bold_white", "magenta"),
      seg("time_24h", "bold_white", "magenta"),
      seg("space", "bold_white", "magenta"),
      seg("arrow_powerline", "magenta", "green"),
      seg("space", "bold_white", "green"),
      seg("directory", "bold_white", "green"),
      seg("space", "bold_white", "green"),
      seg("arrow_powerline", "green", "blue"),
      seg("space", "bold_white", "blue"),
      seg("git_branch", "bold_white", "blue"),
      seg("git_dirty", "bold_yellow", "blue"),
      seg("space", "bold_white", "blue"),
      seg("arrow_powerline", "blue"),
      seg("space"),
    ],
  },
];
