import type { SegmentDefinition, SegmentCategory } from "@/types/prompt";

export const SEGMENT_DEFINITIONS: SegmentDefinition[] = [
  // Prompt Segments
  {
    id: "username",
    label: "Username",
    code: "%n",
    category: "prompt",
    description: "Current username",
    mockValue: "user",
  },
  {
    id: "hostname",
    label: "Hostname",
    code: "%m",
    category: "prompt",
    description: "Short hostname",
    mockValue: "macbook",
  },
  {
    id: "full_hostname",
    label: "Full Hostname",
    code: "%M",
    category: "prompt",
    description: "Full hostname",
    mockValue: "macbook.local",
  },
  {
    id: "directory",
    label: "Directory",
    code: "%~",
    category: "prompt",
    description: "Current directory (with ~ abbreviation)",
    mockValue: "~/project",
  },
  {
    id: "short_dir",
    label: "Short Dir",
    code: "%1~",
    category: "prompt",
    description: "Current directory (last component only)",
    mockValue: "project",
  },
  {
    id: "time_24h",
    label: "Time (24h)",
    code: "%T",
    category: "prompt",
    description: "Current time in 24-hour format",
    mockValue: "14:30",
  },
  {
    id: "time_12h",
    label: "Time (12h)",
    code: "%t",
    category: "prompt",
    description: "Current time in 12-hour format",
    mockValue: "2:30PM",
  },
  {
    id: "date",
    label: "Date",
    code: "%D",
    category: "prompt",
    description: "Current date",
    mockValue: "26-03-16",
  },
  {
    id: "return_code",
    label: "Return Code",
    code: "%?",
    category: "prompt",
    description: "Exit status of last command",
    mockValue: "0",
  },
  {
    id: "jobs",
    label: "Jobs",
    code: "%j",
    category: "prompt",
    description: "Number of background jobs",
    mockValue: "0",
  },
  {
    id: "shell_level",
    label: "Shell Level",
    code: "%L",
    category: "prompt",
    description: "Current shell nesting level",
    mockValue: "1",
  },
  {
    id: "history_number",
    label: "History #",
    code: "%!",
    category: "prompt",
    description: "History event number",
    mockValue: "142",
  },

  // Git Info
  {
    id: "git_branch",
    label: "Git Branch",
    code: '$(git_current_branch)',
    category: "git",
    description: "Current git branch name",
    mockValue: "main",
  },
  {
    id: "git_dirty",
    label: "Dirty/Clean",
    code: '$(git_prompt_status)',
    category: "git",
    description: "Git dirty/clean indicator",
    mockValue: "*",
  },
  {
    id: "git_ahead_behind",
    label: "Ahead/Behind",
    code: '$(git_prompt_ahead)$(git_prompt_behind)',
    category: "git",
    description: "Commits ahead/behind remote",
    mockValue: "+2",
  },
  {
    id: "git_stash",
    label: "Stash Count",
    code: '$(git_prompt_stash_count)',
    category: "git",
    description: "Number of stashed changes",
    mockValue: "1",
  },
  {
    id: "git_untracked",
    label: "Untracked Files",
    code: '$(git_prompt_untracked)',
    category: "git",
    description: "Untracked files indicator",
    mockValue: "?",
  },

  // Decorators — Arrows & Chevrons
  {
    id: "arrow_right",
    label: "Arrow >",
    code: ">",
    category: "decorators",
    description: "Right arrow separator",
    mockValue: ">",
  },
  {
    id: "double_arrow",
    label: "Double Arrow \u00BB",
    code: "\\u00BB",
    category: "decorators",
    description: "Double angle bracket",
    mockValue: "\u00BB",
  },
  {
    id: "chevron",
    label: "Chevron \u276F",
    code: "\\u276F",
    category: "decorators",
    description: "Heavy right-pointing angle",
    mockValue: "\u276F",
  },
  {
    id: "arrow_triangle",
    label: "Triangle \u25B6",
    code: "\\u25B6",
    category: "decorators",
    description: "Right-pointing triangle",
    mockValue: "\u25B6",
  },
  {
    id: "arrow_powerline",
    label: "Powerline",
    code: "\\uE0B0",
    category: "decorators",
    description: "Powerline arrow separator (requires Nerd Font)",
    mockValue: "\u25E2",
  },
  {
    id: "arrow_powerline_thin",
    label: "Powerline Thin",
    code: "\\uE0B1",
    category: "decorators",
    description: "Powerline thin arrow separator (requires Nerd Font)",
    mockValue: "\u276F",
  },
  {
    id: "arrow_right_unicode",
    label: "Arrow \u2192",
    code: "\\u2192",
    category: "decorators",
    description: "Unicode right arrow",
    mockValue: "\u2192",
  },
  {
    id: "arrow_double_right",
    label: "Double \u21D2",
    code: "\\u21D2",
    category: "decorators",
    description: "Double right arrow",
    mockValue: "\u21D2",
  },
  {
    id: "lambda",
    label: "Lambda \u03BB",
    code: "\\u03BB",
    category: "decorators",
    description: "Lambda symbol",
    mockValue: "\u03BB",
  },

  // Decorators — Lines & Boxes
  {
    id: "line_horizontal",
    label: "Line \u2500",
    code: "\\u2500",
    category: "decorators",
    description: "Horizontal line",
    mockValue: "\u2500",
  },
  {
    id: "line_double",
    label: "Double Line \u2550",
    code: "\\u2550",
    category: "decorators",
    description: "Double horizontal line",
    mockValue: "\u2550",
  },
  {
    id: "corner_top_left",
    label: "Corner \u256D",
    code: "\\u256D",
    category: "decorators",
    description: "Rounded top-left corner",
    mockValue: "\u256D",
  },
  {
    id: "corner_bottom_left",
    label: "Corner \u2570",
    code: "\\u2570",
    category: "decorators",
    description: "Rounded bottom-left corner",
    mockValue: "\u2570",
  },
  {
    id: "vertical_line",
    label: "Vertical \u2502",
    code: "\\u2502",
    category: "decorators",
    description: "Vertical line",
    mockValue: "\u2502",
  },
  {
    id: "t_junction",
    label: "T-Junction \u251C",
    code: "\\u251C",
    category: "decorators",
    description: "Left T-junction",
    mockValue: "\u251C",
  },

  // Decorators — Symbols
  {
    id: "star",
    label: "Star \u2605",
    code: "\\u2605",
    category: "decorators",
    description: "Filled star",
    mockValue: "\u2605",
  },
  {
    id: "bullet",
    label: "Bullet \u2022",
    code: "\\u2022",
    category: "decorators",
    description: "Bullet point",
    mockValue: "\u2022",
  },
  {
    id: "diamond",
    label: "Diamond \u25C6",
    code: "\\u25C6",
    category: "decorators",
    description: "Filled diamond",
    mockValue: "\u25C6",
  },
  {
    id: "ellipsis",
    label: "Ellipsis \u2026",
    code: "\\u2026",
    category: "decorators",
    description: "Horizontal ellipsis",
    mockValue: "\u2026",
  },
  {
    id: "tilde",
    label: "Tilde ~",
    code: "~",
    category: "decorators",
    description: "Tilde separator",
    mockValue: "~",
  },
  {
    id: "pipe",
    label: "Pipe |",
    code: "|",
    category: "decorators",
    description: "Pipe separator",
    mockValue: "|",
  },
  {
    id: "dash",
    label: "Dash -",
    code: "-",
    category: "decorators",
    description: "Dash separator",
    mockValue: "-",
  },

  // Decorators — Brackets & Wrappers
  {
    id: "bracket_open",
    label: "[ Open",
    code: "[",
    category: "decorators",
    description: "Opening bracket",
    mockValue: "[",
  },
  {
    id: "bracket_close",
    label: "] Close",
    code: "]",
    category: "decorators",
    description: "Closing bracket",
    mockValue: "]",
  },
  {
    id: "paren_open",
    label: "( Open",
    code: "(",
    category: "decorators",
    description: "Opening parenthesis",
    mockValue: "(",
  },
  {
    id: "paren_close",
    label: ") Close",
    code: ")",
    category: "decorators",
    description: "Closing parenthesis",
    mockValue: ")",
  },
  {
    id: "curly_open",
    label: "{ Open",
    code: "{",
    category: "decorators",
    description: "Opening curly brace",
    mockValue: "{",
  },
  {
    id: "curly_close",
    label: "} Close",
    code: "}",
    category: "decorators",
    description: "Closing curly brace",
    mockValue: "}",
  },
  {
    id: "angle_open",
    label: "\u276E Open",
    code: "\\u276E",
    category: "decorators",
    description: "Heavy left-pointing angle",
    mockValue: "\u276E",
  },
  {
    id: "angle_close",
    label: "\u276F Close",
    code: "\\u276F",
    category: "decorators",
    description: "Heavy right-pointing angle",
    mockValue: "\u276F",
  },

  // Decorators — Spacing & Structure
  {
    id: "space",
    label: "Space",
    code: " ",
    category: "decorators",
    description: "Single space",
    mockValue: " ",
  },
  {
    id: "newline",
    label: "Newline",
    code: "\n",
    category: "decorators",
    description: "Line break (multi-line prompt)",
    mockValue: "\n",
  },
  {
    id: "at_sign",
    label: "@ Sign",
    code: "@",
    category: "decorators",
    description: "At sign separator",
    mockValue: "@",
  },
  {
    id: "colon",
    label: "Colon",
    code: ":",
    category: "decorators",
    description: "Colon separator",
    mockValue: ":",
  },
  {
    id: "dollar",
    label: "$ Prompt",
    code: "$ ",
    category: "decorators",
    description: "Dollar sign prompt ending",
    mockValue: "$ ",
  },
  {
    id: "hash",
    label: "# Prompt",
    code: "# ",
    category: "decorators",
    description: "Hash prompt ending (root)",
    mockValue: "# ",
  },
  {
    id: "percent",
    label: "% Prompt",
    code: "%% ",
    category: "decorators",
    description: "Percent sign prompt ending",
    mockValue: "% ",
  },

  // Plugins
  {
    id: "node_version",
    label: "Node Version",
    code: '$(node -v 2>/dev/null)',
    category: "plugins",
    description: "Node.js version",
    mockValue: "v20.11.0",
  },
  {
    id: "python_venv",
    label: "Python Venv",
    code: '${VIRTUAL_ENV:+$(basename $VIRTUAL_ENV)}',
    category: "plugins",
    description: "Python virtual environment name",
    mockValue: "venv",
  },
  {
    id: "ruby_version",
    label: "Ruby Version",
    code: '$(ruby -v 2>/dev/null | cut -d" " -f2)',
    category: "plugins",
    description: "Ruby version",
    mockValue: "3.2.0",
  },
  {
    id: "aws_profile",
    label: "AWS Profile",
    code: '${AWS_PROFILE:-default}',
    category: "plugins",
    description: "Current AWS profile",
    mockValue: "production",
  },
  {
    id: "kubectl_context",
    label: "K8s Context",
    code: '$(kubectl config current-context 2>/dev/null)',
    category: "plugins",
    description: "Current kubectl context",
    mockValue: "minikube",
  },
  {
    id: "battery_level",
    label: "Battery",
    code: '$(battery_pct_prompt)',
    category: "plugins",
    description: "Battery level percentage",
    mockValue: "85%",
  },
  {
    id: "os_icon",
    label: "OS Icon",
    code: "$(os_icon)",
    category: "plugins",
    description: "Operating system icon (requires Nerd Font)",
    mockValue: "OS",
  },
];

export const CATEGORY_LABELS: Record<SegmentCategory, string> = {
  prompt: "Prompt Segments",
  git: "Git Info",
  colors: "Colors",
  decorators: "Decorators",
  plugins: "Plugins",
};

export const SIDEBAR_CATEGORIES: SegmentCategory[] = [
  "prompt",
  "git",
  "decorators",
  "plugins",
];

export function getSegmentById(id: string): SegmentDefinition | undefined {
  return SEGMENT_DEFINITIONS.find((s) => s.id === id);
}
